line-length = 80
indent-width = 2

# Include notebooks
extend-include = ["*.ipynb"]

# Ignore some import violations when not needed
[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]
"**/{tests,docs,tools}/*" = ["E402", "F401"]