name: Test and deploy for conda 

on: [push]

jobs:
  build-and-publish:
    
    strategy:
      fail-fast: false
      max-parallel: 12
      matrix:
        platform: [windows-latest]
        # platform: [ubuntu-latest, macos-latest]
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        architecture: ["x86", "x64"]
        include:
          - platform: ubuntu-latest
            platform-conda: "Linux"
          - platform: macos-latest
            platform-conda: "MacOSX"
          - platform: windows-latest
            platform-conda: "Windows"
          - architecture: "x86"
            platform-vcvars: "x86"
            platform-msbuild: "Win32"
            architecture-conda: "x86"
          - architecture: "x64"
            platform-vcvars: "x86_amd64"
            platform-msbuild: "x64"
            architecture-conda: "x86_64"
        python-version: [3.6, 3.7]
        exclude:
          - platform: macos-latest
            architecture: "x86"
          - platform: ubuntu-latest
            architecture: "x86"

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout project 
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Visual Studio Command Prompt tool (windows)
      if: contains(matrix.platform, 'windows')
      run: |
        cmd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }}
    - name: Install conda (windows)
      if: contains(matrix.platform, 'windows')
      run: |
        Invoke-WebRequest -OutFile miniconda.exe https://repo.continuum.io/miniconda/Miniconda3-latest-${{matrix.platform-conda}}-${{matrix.architecture-conda}}.exe
        Start-Process -FilePath "miniconda.exe" -ArgumentList "/S","/D=$HOME\miniconda"
        echo '::add-path::C:\Users\runneradmin\miniconda\;C:\Users\runneradmin\miniconda\Scripts\'
      shell: powershell
    - name: Install conda (ubuntu and macos)
      if: contains(matrix.platform, 'windows') == false
      run: |
        wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-${{matrix.platform-conda}}-${{matrix.architecture-conda}}.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "::add-path::$HOME/miniconda/bin"
    - name: Configure conda 
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
    - name: Update conda 
      run: |
        conda update -q conda
    - name: Install build dependencies 
      run: |
        conda install -q conda-build conda-verify
    - name: Build recipe 
      run: |
        conda build -q conda.recipe --python=${{ matrix.python-version }} --output-folder=build
    - name: Add conda channel 
      run: |
        conda config --add channels "file://`pwd`/build"
    - name: Install package
      run: |
        conda create -q -n test-environment python=${{ matrix.python-version }} pyvinecopulib pytest
    - name: Test with pytest
      run: |
        source activate test-environment
        pytest tests -r a

