name: Test and deploy for conda 

on: [push]

jobs:
  build-and-publish:
    strategy:
      # fail-fast: false
      max-parallel: 12
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        platform: [ubuntu-latest]
        # architecture: ["x86", "x64"]
        # include:
        #   - architecture: "x86"
        #     platform-vcvars: "x86"
        #     platform-msbuild: "Win32"
        #   - architecture: "x64"
        #     platform-vcvars: "x86_amd64"
            # platform-msbuild: "x64"
        python-version: [3.6, 3.7]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout project 
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Visual Studio Command Prompt tool
      if: contains(matrix.platform, 'windows')
      run: |
        cmd "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" ${{ matrix.platform-vcvars }}
    - name: Install dependencies
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda update -q conda
        conda install -q conda-build conda-verify pytest
    - name: Build recipe 
      run: |
        conda build -q conda.recipe --python=${{ matrix.python-version }} --output-folder=build
    - name: Add conda channel 
      run: |
        conda config --add channels "file://`pwd`/build"
    - name: Install package 
      run: |
        conda create -q -n test-environment python=${{ matrix.python-version }} pyvinecopulib pytest
        source activate test-environment
        conda info --envs
    - name: Test with pytest
      run: |
        pytest tests -r a

